version: 1.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
build:
  project: BearBuildTool.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: pack_build.cmd
artifacts:
- path: temp/release.7z
  name: release.7z
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: BearBuildTool (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Rg/4it4SOJP02wVZf3z/fZ0Mo2++MIL64NfRnYOHKuQaW3aEQSB2i7arLNzX4Q3k
  artifact: release.7z
  draft: false
  prerelease: false
  on:
    configuration: Release