os: Visual Studio 2017
version: '{build}'
skip_tags: true

configuration:
- Debug
- Release

platform:
- Any CPU

matrix:
  allow_failures:
    - platform: Any CPU
      configuration: Debug
    - platform: Any CPU
      configuration: Release


build:
  project: BearBuildTool.sln
  parallel: true
  verbosity: minimal

test: off

after_build:
- cmd: pack_build.cmd

artifacts:
- path: temp/Release.7z
  name: Release.7z

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: BearBuildTool (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: 66f48990f93155534a8b6308e24e15e7e461ef12
  artifact:
    Release.7z
  draft: true
  force_update: true